spring:
  application:
    name: conversia
  profiles:
    active: dev
server:
  port: 8080


huggingface:
  api-key: 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
  model: tiiuae/falcon-7b-instruct


# langchain4j:
#   open-ai:
#     chat-model:
#       api-key: demo
#       model-name: gpt-3.5-turbo
#       log-requests: true
#       log-responses: true