spring:
  application:
    name: conversia
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/conversia
      database: conversia
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: 123abc456def789ghi012jkl345mno678pqr901stu234vwx567yz890
  expiration: 86400000

huggingface:
  api-key: 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
  model: mistralai/Mistral-7B-Instruct-v0.3
mistral:
  api:
    key: ag:59397f79:20250604:untitled-agent:418ddaf8  # D9M5ZARAmKHHsbV6y8xdTEMoBxiBDkXZ
    model: mistral-medium   # mistral-7b-instruct-v0.1
logging:
  level:
    com.avs: DEBUG
    org.springframework: DEBUG
    org.springframework.security: DEBUG