spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/conversia}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/conversia}
      database: conversia

logging:
  level:
    com.avs: INFO
    org.springframework: WARN
    org.springframework.security: WARN